# Generated by Django 3.2.8 on 2021-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211119_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='owner',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.EventTag'),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='name',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
