# Generated by Django 3.2.8 on 2021-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventreview_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='reg_dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
