# Generated by Django 3.2.8 on 2021-12-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211203_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_opt',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
