# Generated by Django 3.2.8 on 2022-01-25 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=500)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('replied', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['replied', '-created'],
            },
        ),
    ]
