# Generated by Django 3.2.8 on 2021-11-30 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_to',
            field=models.CharField(choices=[('ALL', 'All'), ('GM', 'General Members'), ('AL', 'Alumnus'), ('FC', 'Faculty')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
