# Generated by Django 3.2.8 on 2021-11-25 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0019_alter_moderator_moderator_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='EblogCategorie',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eblog',
            fields=[
                ('title', models.CharField(max_length=3000)),
                ('body', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog-thumbnail/')),
                ('published_timestamp', models.DateTimeField()),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('eblog_cats', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eblogs.eblogcategorie')),
            ],
        ),
    ]
