# Generated by Django 3.2.8 on 2021-12-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblogs', '0003_eblogreview_eblogreviewreplie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eblogtag',
            name='blog',
        ),
        migrations.DeleteModel(
            name='EblogReviewReplie',
        ),
    ]
