# Generated by Django 3.2.8 on 2022-01-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblogs', '0005_eblog_eblog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eblog',
            options={'ordering': ['-published_timestamp']},
        ),
    ]
