# Generated by Django 3.2.8 on 2022-02-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220215_2305'),
        ('eblogs', '0006_alter_eblog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eblog',
            name='blogger',
        ),
        migrations.CreateModel(
            name='EblogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
    ]
