# Generated by Django 3.2.8 on 2022-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblogs', '0007_auto_20220218_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='eblog',
            name='blog_authors',
            field=models.ManyToManyField(to='eblogs.EblogAuthor'),
        ),
        migrations.AddField(
            model_name='eblog',
            name='docx_drive_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='eblog',
            name='keywords',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='eblog',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
