# Generated by Django 3.2.8 on 2022-02-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220215_2305'),
        ('eblogs', '0008_auto_20220218_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='eblog',
            name='other_authors_username',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='eblog',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
    ]
