# Generated by Django 3.2.8 on 2022-01-27 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0019_alter_moderator_moderator_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JournalKeyword',
            fields=[
                ('keyword', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalsCategory',
            fields=[
                ('category', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('title', models.CharField(max_length=3000)),
                ('abstract', models.TextField()),
                ('pdf_drive_link', models.CharField(max_length=10000)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_timestamp', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('all_journals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journalscategory')),
                ('authors', models.ManyToManyField(to='journals.JournalAuthor')),
                ('keyword', models.ManyToManyField(to='journals.JournalKeyword')),
            ],
        ),
    ]
