# Generated by Django 3.2.8 on 2022-02-08 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20220201_2123'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalReview',
            fields=[
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journals')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
