# Generated by Django 3.2.8 on 2021-10-27 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('std_alum', models.CharField(choices=[('student', 'Student'), ('Alumnus', 'Alumnus')], max_length=200)),
                ('institution', models.CharField(choices=[('EWU', 'East West University'), ('BRAC', 'BRAC University'), ('DU', 'Dhaka University')], max_length=200)),
                ('department', models.CharField(choices=[('ECO', 'Department of Economics'), ('BBA', 'Department of Business Administration')], max_length=200)),
                ('uni_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('std_id', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('about_yourself', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-')], max_length=200)),
                ('location', models.CharField(choices=[('banasree', 'Banasree'), ('aftabnagar', 'Aftabnagar')], max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
