# Generated by Django 3.2.8 on 2021-10-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211029_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='std_alum',
            field=models.CharField(choices=[('student', 'Student'), ('alumnus', 'Alumnus')], max_length=200),
        ),
    ]
