# Generated by Django 3.2.8 on 2021-10-30 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211030_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='headline',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=200),
        ),
    ]
