# Generated by Django 3.2.8 on 2021-11-04 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211030_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveCommitte',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('ec_start_date', models.DateField()),
                ('ec_current', models.BooleanField(default=False)),
                ('ec_end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_coordinator', to='user.profile', verbose_name='Event Coordinator')),
                ('general_secretary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_secretary', to='user.profile', verbose_name='General Secretary')),
                ('head_of_logistics', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_of_logistics', to='user.profile', verbose_name='Head of Logistics')),
                ('joint_secretary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='joint_secretary', to='user.profile', verbose_name='Joint Secretary')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='user.profile', verbose_name='President')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treasurer', to='user.profile', verbose_name='Treasurer')),
                ('vice_president', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vice_president', to='user.profile', verbose_name='Vice President')),
            ],
        ),
    ]
