# Generated by Django 3.2.8 on 2021-11-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211104_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExecutiveCommitties',
            new_name='ExecutiveCommittiee',
        ),
    ]
