# Generated by Django 3.2.8 on 2021-11-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_executivecommitties_executivecommittiee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivecommittiee',
            name='event_coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_coordinator', to='user.profile', verbose_name='Event Coordinator'),
        ),
        migrations.AlterField(
            model_name='executivecommittiee',
            name='general_secretary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_secretary', to='user.profile', verbose_name='General Secretary'),
        ),
        migrations.AlterField(
            model_name='executivecommittiee',
            name='head_of_logistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_of_logistics', to='user.profile', verbose_name='Head of Logistics'),
        ),
        migrations.AlterField(
            model_name='executivecommittiee',
            name='joint_secretary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='joint_secretary', to='user.profile', verbose_name='Joint Secretary'),
        ),
        migrations.AlterField(
            model_name='executivecommittiee',
            name='president',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='user.profile', verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='executivecommittiee',
            name='treasurer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treasurer', to='user.profile', verbose_name='Treasurer'),
        ),
        migrations.AlterField(
            model_name='executivecommittiee',
            name='vice_president',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vice_president', to='user.profile', verbose_name='Vice President'),
        ),
    ]
