# Generated by Django 3.2.8 on 2021-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='mod_check',
            field=models.BooleanField(default=True),
        ),
    ]
