# Generated by Django 3.2.8 on 2021-11-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_moderator_mod_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_verification',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
