# Generated by Django 3.2.8 on 2021-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20211105_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_verification',
            field=models.ImageField(blank=True, null=True, upload_to='profile-id-verification/'),
        ),
    ]
