# Generated by Django 3.2.8 on 2021-11-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_profile_id_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['verified', '-created']},
        ),
    ]
