# Generated by Django 3.2.8 on 2021-11-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='moderator_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator_one', to='user.profile', verbose_name='moderator_one'),
        ),
    ]
